import "./globals.css";
import { ThemeProvider } from "../../components/ThemeProvider"; //dark mode theme provider
export const metadata = {
  title: "OOP_Website",
  description: "Generated by create next app",
};
import Navbar from "../../components/navbar";
import Footer from "../../components/footer";
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <Navbar/>
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
