import "./globals.css";
import { ThemeProvider } from "../../components/ThemeProvider";

export const metadata = {
  title: "OOPMart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
